/**
 * build.js — Compact SaaS Components build pipeline
 *
 * Reads source CSS files, concatenates into dist/free/ and dist/pro/,
 * minifies via clean-css, copies engine/component files, and writes index.js.
 *
 * Usage:  node scripts/build.js
 * Deps:   npm install clean-css
 */

const fs = require('fs');
const path = require('path');

// ---------------------------------------------------------------------------
// Resolve paths relative to the project root (one level up from scripts/)
// ---------------------------------------------------------------------------
const ROOT = path.resolve(__dirname, '..');
const src  = (...seg) => path.join(ROOT, 'src',  ...seg);
const dist = (...seg) => path.join(ROOT, 'dist', ...seg);
const read = (p) => fs.readFileSync(p, 'utf8');
const write = (p, data) => { fs.mkdirSync(path.dirname(p), { recursive: true }); fs.writeFileSync(p, data); };

// Ensure output dirs exist
fs.mkdirSync(dist('free'), { recursive: true });
fs.mkdirSync(dist('pro'),  { recursive: true });

// ---------------------------------------------------------------------------
// 1. Read source files
// ---------------------------------------------------------------------------
const tokens   = read(src('css', 'tokens.css'));
const core     = read(src('css', 'core.css'));

const themes = {
  clean:   read(src('css', 'themes', 'clean.css')),
  graphite: read(src('css', 'themes', 'graphite.css')),
  dracula:  read(src('css', 'themes', 'dracula.css')),
  davinci:  read(src('css', 'themes', 'davinci.css')),
  casual:   read(src('css', 'themes', 'casual.css')),
};

// ---------------------------------------------------------------------------
// 2. Concatenate into bundles
// ---------------------------------------------------------------------------
// Free:  tokens + core + 3 themes (clean, graphite, dracula)
// Pro:   tokens + core + all 5 themes

const freeThemes = [themes.clean, themes.graphite, themes.dracula].join('\n\n');
const proThemes  = Object.values(themes).join('\n\n');

const freeBundle = `${tokens}\n\n${core}\n\n${freeThemes}`;
const proBundle  = `${tokens}\n\n${core}\n\n${proThemes}`;

// ---------------------------------------------------------------------------
// 3. Minify with clean-css
// ---------------------------------------------------------------------------
let CleanCSS;
try {
  CleanCSS = require('clean-css');
} catch (_) {
  console.error('ERROR: clean-css is not installed. Run: npm install clean-css');
  process.exit(1);
}

const minifier = new CleanCSS({ level: 2, returnPromise: false });

const freeMin = minifier.minify(freeBundle);
const proMin  = minifier.minify(proBundle);

if (freeMin.errors.length) {
  console.error('Free bundle minification errors:', freeMin.errors);
  process.exit(1);
}
if (proMin.errors.length) {
  console.error('Pro bundle minification errors:', proMin.errors);
  process.exit(1);
}

// Write both unminified (for debugging) and minified
write(dist('free', 'saasblocks.css'), freeBundle);
write(dist('free', 'saasblocks.min.css'), freeMin.styles);
write(dist('pro',  'saasblocks.css'), proBundle);
write(dist('pro',  'saasblocks.min.css'), proMin.styles);

// ---------------------------------------------------------------------------
// 4. Copy engine + components
// ---------------------------------------------------------------------------
function copyDir(srcDir, destDir) {
  fs.mkdirSync(destDir, { recursive: true });
  const entries = fs.readdirSync(srcDir, { withFileTypes: true });
  for (const e of entries) {
    const s = path.join(srcDir, e.name);
    const d = path.join(destDir, e.name);
    if (e.isDirectory()) {
      copyDir(s, d);
    } else {
      fs.copyFileSync(s, d);
    }
  }
}

// Copy to free dist
copyDir(src('engine'),     dist('free', 'engine'));
copyDir(src('components'), dist('free', 'components'));

// Copy to pro dist
copyDir(src('engine'),     dist('pro', 'engine'));
copyDir(src('components'), dist('pro', 'components'));

// ---------------------------------------------------------------------------
// 5. Create index.js entry points
// ---------------------------------------------------------------------------
const indexJS = `/**
 * Compact SaaS Components — entry point
 *
 * Import this file to load all components.
 * CSS must be loaded separately via saasblocks.css or saasblocks.min.css.
 */

// This file is auto-generated by scripts/build.js

// Component modules are loaded on-demand via the gallery engine.
// If you want to register all components at once, import them here.

const fs = require('fs');
const path = require('path');

// Auto-discover and require all component .js files
const componentsDir = path.join(__dirname, 'components');
function loadComponents(dir) {
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const e of entries) {
    const full = path.join(dir, e.name);
    if (e.isDirectory()) {
      loadComponents(full);
    } else if (e.name.endsWith('.js')) {
      require(full);
    }
  }
}

loadComponents(componentsDir);

module.exports = { version: 'VERSION_PLACEHOLDER' };
`;

write(dist('free', 'index.js'), indexJS.replace('VERSION_PLACEHOLDER', 'free'));
write(dist('pro',  'index.js'), indexJS.replace('VERSION_PLACEHOLDER', 'pro'));

// ---------------------------------------------------------------------------
// 5b. Create standalone IIFE gallery bundle from ES modules
// ---------------------------------------------------------------------------
// This reads all engine and component source files, strips import/export,
// and produces a single IIFE bundle that works as a drop-in replacement
// for the original compact-saas-component-gallery.js

function createGalleryBundle() {
  // ── Read engine source files ──
  const engineFiles = [
    'helpers.js',
    'state.js',
    'themes.js',
    'renderer.js',
    'interactions.js',
  ];

  const engineCode = {};
  for (const f of engineFiles) {
    engineCode[f.replace('.js', '')] = read(src('engine', f));
  }

  // ── Read all component group files ──
  const componentDirs = fs.readdirSync(src('components'), { withFileTypes: true })
    .filter(e => e.isDirectory())
    .map(e => e.name);

  const allComponentArrays = [];
  for (const dir of componentDirs) {
    const compPath = src('components', dir, 'index.js');
    if (fs.existsSync(compPath)) {
      let content = read(compPath);
      // Strip the import line
      content = content.replace(/^import\s+.*?;\s*\n/m, '');
      // Strip export default
      content = content.replace(/^export\s+default\s+/m, '');
      allComponentArrays.push(content.trim());
    }
  }

  // ── Process engine files: strip import/export ──
  function stripModuleSyntax(code) {
    // Remove import lines (including multi-line imports)
    code = code.replace(/^import\s+.*?(?:from\s+.*?)?;\s*$/gm, '');
    // Remove export keyword from function/const declarations
    code = code.replace(/^export\s+(default\s+)?/gm, '');
    return code.trim();
  }

  const helpersSrc     = stripModuleSyntax(engineCode.helpers);
  const stateSrc       = stripModuleSyntax(engineCode.state);
  const themesSrc      = stripModuleSyntax(engineCode.themes);
  const rendererSrc    = stripModuleSyntax(engineCode.renderer);

  // interactions.js needs special handling: replace dynamic import with direct calls
  let interactionsSrc  = engineCode.interactions;
  // Strip imports
  interactionsSrc = interactionsSrc.replace(/^import\s+.*?;\s*$/gm, '');
  // Strip export keywords
  interactionsSrc = interactionsSrc.replace(/^export\s+/gm, '');
  // Replace the dynamic import block for theme switching
  // The block has nested braces, so we match from var themeBtn to the return;
  interactionsSrc = interactionsSrc.replace(
    /var themeBtn = event\.target\.closest\("\[data-theme-key\]"\);\s*\n\s*if \(themeBtn\) \{[\s\S]*?import\("\.\/themes\.js"\)[\s\S]*?\n\s*return;\s*\n\s*\}/,
    'var themeBtn = event.target.closest("[data-theme-key]");\n      if (themeBtn) {\n        applyTheme(themeBtn.dataset.themeKey);\n        renderThemeToggles(themes, els.themeToggles);\n        return;\n      }'
  );
  interactionsSrc = interactionsSrc.trim();

  // ── Assemble the IIFE bundle ──
  const bundle = [
    '/**',
    ' * SaaSBlocks — Compact SaaS Component Gallery Bundle',
    ' * Auto-generated from modular source by scripts/build.js',
    ' * Do not edit directly.',
    ' */',
    '',
    '(function () {',
    '',
    '  // ═══════════════════════════════════════════════',
    '  //  HELPERS',
    '  // ═══════════════════════════════════════════════',
    '',
    indentLines(helpersSrc, 2),
    '',
    '  // ═══════════════════════════════════════════════',
    '  //  COMPONENT DATA',
    '  // ═══════════════════════════════════════════════',
    '',
    '  window.galleryItems = ' + allComponentArrays.join(',\n\n') + ';',
    '',
    '  // ═══════════════════════════════════════════════',
    '  //  STATE',
    '  // ═══════════════════════════════════════════════',
    '',
    '  var els = {};',
    '',
    indentLines(stateSrc, 2),
    '',
    '  // ═══════════════════════════════════════════════',
    '  //  THEMES',
    '  // ═══════════════════════════════════════════════',
    '',
    indentLines(themesSrc, 2),
    '',
    '  // ═══════════════════════════════════════════════',
    '  //  RENDERER',
    '  // ═══════════════════════════════════════════════',
    '',
    indentLines(rendererSrc, 2),
    '',
    '  // ═══════════════════════════════════════════════',
    '  //  INTERACTIONS',
    '  // ═══════════════════════════════════════════════',
    '',
    indentLines(interactionsSrc, 2),
    '',
    '  // ═══════════════════════════════════════════════',
    '  //  INIT',
    '  // ═══════════════════════════════════════════════',
    '',
    '  function render() {',
    '    var groupList = groups(window.galleryItems);',
    '    renderFilters(groupList, state, els.filters);',
    '    var filtered = filteredItems(window.galleryItems);',
    '    renderGallery(filtered, els.gallery);',
    '  }',
    '',
    '  function runTests() {',
    '    try {',
    '      console.assert(window.galleryItems.length >= 120, "gallery has many items");',
    '      console.assert(',
    '        document.querySelectorAll(".doc-card").length >= window.galleryItems.length,',
    '        "all items render initially"',
    '      );',
    '      console.assert(',
    '        document.querySelectorAll("[data-filter]").length > 10,',
    '        "filters render"',
    '      );',
    '    } catch (e) {',
    '      // Silently ignore test failures in production',
    '    }',
    '  }',
    '',
    '  function init() {',
    '    els.gallery = document.getElementById("gallery");',
    '    els.filters = document.getElementById("filters");',
    '    els.search = document.getElementById("search");',
    '    els.themeToggles = document.getElementById("themeToggles");',
    '',
    '    // Apply saved theme on start',
    '    var saved = getSavedTheme();',
    '    applyTheme(saved);',
    '',
    '    render();',
    '    renderThemeToggles(themes, els.themeToggles);',
    '    bind(els, state, render);',
    '    hydrateInteractive(document);',
    '    runTests();',
    '  }',
    '',
    '  // ═══════════════════════════════════════════════',
    '  //  EXPOSE & BOOT',
    '  // ═══════════════════════════════════════════════',
    '',
    '  window.CompactGalleryUI = {',
    '    hydrate: hydrateInteractive,',
    '    refreshIcons: refreshIcons,',
    '  };',
    '',
    '  if (document.readyState === "loading") {',
    '    document.addEventListener("DOMContentLoaded", init);',
    '  } else {',
    '    init();',
    '  }',
    '',
    '})();',
    '',
  ].join('\n');

  return bundle;
}

/**
 * Indents every non-empty line of a source block by a given number of spaces.
 */
function indentLines(src, spaces) {
  const prefix = ' '.repeat(spaces);
  return src.split('\n').map(function (line) {
    // Don't indent empty lines
    if (line.trim() === '') return '';
    return prefix + line;
  }).join('\n');
}

const galleryBundle = createGalleryBundle();
write(dist('gallery.bundle.js'), galleryBundle);

// ---------------------------------------------------------------------------
// 6. Log output
// ---------------------------------------------------------------------------
console.log('──────────────────────────────────────────');
console.log('  Compact SaaS Components — Build Report');
console.log('──────────────────────────────────────────');
console.log('');
console.log('  FREE tier:');
console.log('    CSS unminified : ' + (freeBundle.length / 1024).toFixed(1) + ' KB');
console.log('    CSS minified   : ' + (freeMin.styles.length / 1024).toFixed(1) + ' KB');
console.log('    Themes         : clean, graphite, dracula');
console.log('    Output         : dist/free/');
console.log('');
console.log('  PRO tier:');
console.log('    CSS unminified : ' + (proBundle.length / 1024).toFixed(1) + ' KB');
console.log('    CSS minified   : ' + (proMin.styles.length / 1024).toFixed(1) + ' KB');
console.log('    Themes         : clean, graphite, dracula, davinci, casual');
console.log('    Output         : dist/pro/');
console.log('');
console.log('  Gallery bundle:');
console.log('    JS bundle      : ' + (galleryBundle.length / 1024).toFixed(1) + ' KB');
console.log('    Output         : dist/gallery.bundle.js');
console.log('');
console.log('  ✓ Build complete.');
console.log('──────────────────────────────────────────');
