import { icon, button, chip, toggle } from '../../engine/helpers.js';

export default [
  {
    name: "Login form",
    group: "Forms",
    notes: "Stacked auth",
    code: `<div class="stack"><input class="input" placeholder="Email"><input class="input" placeholder="Password" type="password"><div class="row between"><label class="row text"><input type="checkbox"> Remember</label><button class="btn ghost">Forgot?</button></div>${button("Sign in", "log-in", "primary")}${button("Create account", "user-plus")}</div>`,
  },
  {
    name: "Inline comment",
    group: "Forms",
    notes: "Textarea + submit",
    code: `<div class="row"><textarea class="textarea" placeholder="Write a comment..."></textarea>${button("Send", "send", "primary")}</div>`,
  },
  {
    name: "Search command",
    group: "Forms",
    notes: "Input + action",
    code: `<div class="row"><input class="input" placeholder="Search actions, pages, users...">${button("Go", "search", "primary")}</div>`,
  },
  {
    name: "Invite user",
    group: "Forms",
    notes: "Email capture",
    code: `<div class="row"><input class="input" placeholder="Invite by email">${button("Invite", "user-plus", "primary")}</div>`,
  },
  {
    name: "Search filter",
    group: "Forms",
    notes: "Input + filter",
    code: `<div class="row between"><div class="row"><input class="input" placeholder="Search..."><button class="btn">Active</button></div>${button("Filter", "sliders-horizontal")}</div>`,
  },
  {
    name: "Two fields",
    group: "Forms",
    notes: "Paired inputs",
    code: `<div class="grid2"><input class="input" placeholder="First name"><input class="input" placeholder="Last name"></div>`,
  },
  {
    name: "Select row",
    group: "Forms",
    notes: "Select + apply",
    code: `<div class="row"><select class="select"><option>Default</option></select>${button("Apply")}</div>`,
  },
  {
    name: "File upload",
    group: "Forms",
    notes: "Drop target",
    code: `<div class="stack" style="place-items:center;text-align:center">${chip("Upload", "blue")}<div class="strong">Drop files here</div><div class="text">Assets or documents</div>${button("Browse", "folder-open")}</div>`,
  },
  {
    name: "Date range",
    group: "Forms",
    notes: "Start/end",
    code: `<div class="grid2"><input class="input" type="date"><input class="input" type="date"></div>`,
  },
  {
    name: "Copy field",
    group: "Forms",
    notes: "URL field",
    code: `<div class="row"><input class="input" value="https://app.example/link">${button("Copy", "copy")}</div>`,
  },
  {
    name: "Title subtitle",
    group: "Forms",
    notes: "Checkbox fields",
    code: `<div class="grid2"><div class="row"><input type="checkbox" checked><input class="input" placeholder="Title"></div><div class="row"><input type="checkbox" checked><input class="input" placeholder="Subtitle"></div></div>`,
  },
  {
    name: "Field labels",
    group: "Forms",
    notes: "Label + input",
    code: `<div class="grid2"><label class="field-label"><span>Workspace</span><input class="input" value="Tasktok"></label><label class="field-label"><span>Slug</span><input class="input" value="tasktok"></label></div>`,
  },
  {
    name: "Input with icon",
    group: "Forms",
    notes: "Inline search",
    code: `<div class="row"><button class="btn icon-only">${icon("search")}</button><input class="input" placeholder="Find record"></div>`,
  },
  {
    name: "Amount input",
    group: "Forms",
    notes: "Prefix control",
    code: `<div class="row"><button class="btn">$</button><input class="input" value="1240.00"><button class="btn">USD</button></div>`,
  },
  {
    name: "Stepper input",
    group: "Forms",
    notes: "Numeric stepper",
    code: `<div class="row"><button class="btn icon-only" data-step="-1">${icon("minus")}</button><input class="input" value="3" data-step-value><button class="btn icon-only" data-step="1">${icon("plus")}</button></div>`,
  },
  {
    name: "Password row",
    group: "Forms",
    notes: "Field action",
    code: `<div class="row"><input class="input" type="password" value="secret"><button class="btn icon-only" data-password-toggle>${icon("eye")}</button></div>`,
  },
  {
    name: "Validation field",
    group: "Forms",
    notes: "Border needed for field",
    code: `<div class="stack"><input class="input" value="hugo@app"><div class="row">${chip("Invalid", "red")}<span class="text">Use a full email address</span></div></div>`,
  },
  {
    name: "Radio group",
    group: "Forms",
    notes: "Choices no panel",
    code: `<div class="stack"><label class="row"><span class="radio active"></span><span class="text">Owner</span></label><label class="row"><span class="radio"></span><span class="text">Editor</span></label></div>`,
  },
  {
    name: "Checkbox group",
    group: "Forms",
    notes: "Checklist controls",
    code: `<div class="stack"><label class="row"><span class="check active">${icon("check")}</span><span class="text">Header</span></label><label class="row"><span class="check"></span><span class="text">Footer</span></label></div>`,
  },
  {
    name: "Slider row",
    group: "Forms",
    notes: "Native compact",
    code: `<div class="row between"><span class="text">Opacity</span><input style="width:120px" type="range" value="64"><span class="tiny">64%</span></div>`,
  },
  {
    name: "Token input",
    group: "Forms",
    notes: "Tags + input",
    code: `<div class="row">${chip("Admin")}${chip("Clinic")}<input class="input" placeholder="Add tag"></div>`,
  },
  {
    name: "Color picker",
    group: "Forms",
    notes: "Swatch row",
    code: `<div class="row between"><span class="text">Accent</span><div class="row"><span class="tag-dot" style="background:#2563eb;width:14px;height:14px"></span><span class="tag-dot" style="background:#059669;width:14px;height:14px"></span><span class="tag-dot" style="background:#d97706;width:14px;height:14px"></span><span class="tag-dot" style="background:#dc2626;width:14px;height:14px"></span></div></div>`,
  },
  {
    name: "Time picker",
    group: "Forms",
    notes: "Hour/min inputs",
    code: `<div class="row"><input class="input" style="width:44px" value="09"><span class="text">:</span><input class="input" style="width:44px" value="30"><select class="select" style="width:60px"><option>AM</option></select></div>`,
  },
  {
    name: "Phone input",
    group: "Forms",
    notes: "Country + number",
    code: `<div class="row"><button class="btn" style="width:40px">+1</button><input class="input" placeholder="(555) 123-4567"></div>`,
  },
  {
    name: "URL input",
    group: "Forms",
    notes: "Link field",
    code: `<div class="row"><span class="chip" style="border-radius:5px 0 0 5px;border-right:0">https://</span><input class="input" value="mysite.com/page" style="border-radius:0 5px 5px 0"></div>`,
  },
  {
    name: "Currency field",
    group: "Forms",
    notes: "Money input",
    code: `<div class="row"><button class="btn" style="width:32px">$</button><input class="input" value="1,250.00" style="text-align:right"><select class="select" style="width:52px"><option>USD</option></select></div>`,
  },
  {
    name: "Search results",
    group: "Forms",
    notes: "Live results",
    code: `<div class="list"><div class="list-row"><span class="text">Getting started guide</span><span class="tiny">Docs</span></div><div class="list-row"><span class="text">API reference</span><span class="tiny">Dev</span></div><div class="list-row"><span class="text">Billing settings</span><span class="tiny">Admin</span></div></div>`,
  },
  {
    name: "Filter bar",
    group: "Forms",
    notes: "Multi filter row",
    code: `<div class="row wrap"><select class="select" style="width:70px"><option>Status</option></select><select class="select" style="width:80px"><option>Priority</option></select><input class="input" style="width:80px" placeholder="Search">${button("Clear")}</div>`,
  },
  {
    name: "Multi select chips",
    group: "Forms",
    notes: "Chip selector",
    code: `<div class="row wrap">${chip("Design", "blue")}${chip("Dev", "blue")}${chip("Marketing")}<button class="btn">+ Add</button></div>`,
  },
];
